export const ORGANIZATION_CONFIG = {
  name: "TechFi Labs",
  alternateName: "The Technology Fiction",
  initials: "TF",
  tagline: "AI-First Automation Studio & Salesforce Delivery",
  description:
    "TechFi Labs is an AI-first automation studio with deep Salesforce delivery expertise based in Jaipur and Ajmer, India, serving global enterprise clients across US, UK, UAE, and India.",
  url: "https://www.techfilabs.com",
  domain: "www.techfilabs.com",
  logo: "/techfilabs_logo_2026.png",
  logoUrl: "https://www.techfilabs.com/techfilabs_logo_2026.png",
  googleSiteVerification: "google44a1b859b54e70e0",
  googleAnalyticsId: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID || "",
  contact: {
    email: "contact.team@techfilabs.com",
    phone: "+91 7976111087",
    phoneFormatted: "+91 79761 11087",
    address: "Jaipur, Rajasthan 302001, India",
    streetAddress: "Jaipur, Rajasthan 302001",
    city: "Jaipur",
    region: "Rajasthan",
    postalCode: "302001",
    country: "India",
    countryCode: "IN",
  },
  geo: {
    region: "IN-RJ",
    placename: "Jaipur, Ajmer, Rajasthan, India",
    position: "26.9124;75.7873",
    icbm: "26.9124, 75.7873",
    latitude: 26.9124,
    longitude: 75.7873,
  },
  social: {
    facebook: "https://www.facebook.com/thetechnologyfiction/",
    linkedin: "https://www.linkedin.com/company/the-technology-fiction/",
    instagram: "#",
  },
  areasServed: [
    "Jaipur",
    "Ajmer",
    "India",
    "United States",
    "United Kingdom",
    "United Arab Emirates",
    "Global",
  ],
  services: [
    "AI Agents",
    "Workflow Automation",
    "n8n Workflows",
    "WhatsApp AI Integration",
    "Email AI Automation",
    "Salesforce Consulting",
    "Salesforce Data Migration",
    "Mobile App Development",
    "Python Automation",
  ],
} as const;

export type OrganizationConfig = typeof ORGANIZATION_CONFIG;
