export const ORGANIZATION_CONFIG = {
  name: "TechFi Labs",
  alternateName: "The Technology Fiction",
  initials: "TF",
  tagline: "AI-First Automation Studio & Salesforce Delivery",
  description:
    "TechFi Labs is an AI automation, Salesforce, and custom engineering company based in Jaipur, Rajasthan, India, supporting business and consulting teams globally.",
  url: "https://www.techfilabs.com",
  domain: "www.techfilabs.com",
  logo: "/techfilabs_logo_2026.png",
  logoUrl: "https://www.techfilabs.com/techfilabs_logo_2026.png",
  socialImage: "/og-techfi-labs.png",
  socialImageUrl: "https://www.techfilabs.com/og-techfi-labs.png",
  googleSiteVerification: "google44a1b859b54e70e0",
  googleAnalyticsId: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID || "",
  contact: {
    email: "contact.team@techfilabs.com",
    phone: "+91 7976111087",
    phoneFormatted: "+91 79761 11087",
    address: "Jaipur, Rajasthan 302001, India",
    streetAddress: "Jaipur, Rajasthan 302001",
    city: "Jaipur",
    region: "Rajasthan",
    postalCode: "302001",
    country: "India",
    countryCode: "IN",
  },
  geo: {
    region: "IN-RJ",
    placename: "Jaipur, Ajmer, Rajasthan, India",
    position: "26.9124;75.7873",
    icbm: "26.9124, 75.7873",
    latitude: 26.9124,
    longitude: 75.7873,
  },
  social: {
    facebook: "https://www.facebook.com/techfilabsindia/",
    linkedin: "https://www.linkedin.com/company/the-technology-fiction/",
    instagram: "https://www.instagram.com/techfilabsindia?utm_source=ig_web_button_share_sheet&stkn=ZDNlZDc0MzIxNw==",
  },
  areasServed: [
    "Jaipur",
    "Ajmer",
    "India",
    "Banglore",
    "Mumbai",
    "Delhi",
    "Chennai",
    "Kolkata",
    "Pune",
    "Hyderabad",
    "Ahmedabad",
    "Chandigarh",
    "Gurgaon",
    "Noida",
    "US",
    "UK",
    "United States",
    "United Kingdom",
    "United Arab Emirates",
    "Global",
  ],
  services: [
    "AI Agents",
    "Workflow Automation",
    "n8n Workflows",
    "WhatsApp AI Integration",
    "Email AI Automation",
    "Salesforce Consulting",
    "Salesforce Data Migration",
    "Mobile App Development",
    "Python Automation",
    "Salesforce Development",
    "Salesforce Integration",
    "Salesforce Lightning Development",
    "Salesforce Apex Development",
    "Salesforce Visualforce Development",
    "Salesforce LWC Development",
    "Salesforce API Integration",
    "Salesforce Customization",
    "Salesforce App Development",
    "Managed Services",
    "Agentforce",
    "AI Security",
    "AI Governance",
    "Salesforce Architecture",
    "Appexchange App Development",
    "Python Development",
    "Fast API",
    "AWS",
    "Website Development",
    "Shopify Website",
    "Instagram Automation",
    "Auto Replies",
    "Social Media AUto Posting",
    "Orgready.in",
    "Sentinel",
    "FieldLens",
    "Bookverse",
    "Rangmanch",
  ],
} as const;

export type OrganizationConfig = typeof ORGANIZATION_CONFIG;
