import type { CaseStudy } from "@/types/index";

export const CASE_STUDIES_DATA: CaseStudy[] = [
  {
    slug: "ctccs-clinical-trial-contact-center-solution",
    title: "Clinical Trial Contact Center Solution on Salesforce",
    industry: "Life Sciences / Clinical Trial Operations",
    period: "Representative Delivery Experience",
    summary:
      "Delivered a Salesforce-based contact center solution supporting patient engagement, clinical site coordination, hotline operations, and safety workflows in a regulated life sciences environment.",
    outcomes: [
      "Patient concierge and clinical trial hotline workflows",
      "Virtual research coordination support",
      "Adverse event intake and escalation",
      "Compliance-focused case management",
      "Audit trail, SLA, and communication tracking",
      "Site and participant lifecycle architecture",
      "Go-live and hypercare support",
    ],
    keywords: [
      "Salesforce Life Sciences implementation",
      "Clinical trial contact center Salesforce",
      "FDA compliance Salesforce workflows",
      "Adverse event intake Salesforce",
      "Computer system validation IQ OQ PQ",
    ],
    technologies: [
      "Salesforce CRM",
      "Apex",
      "LWC",
      "Flows",
      "Gearset",
      "Azure DevOps",
      "Agile Delivery",
    ],
  },
  {
    slug: "rems-compliance-platform-experience-cloud-portal",
    title: "REMS Compliance Platform & Experience Cloud Portal",
    industry: "Healthcare / Life Sciences",
    period: "Representative Delivery Experience",
    summary:
      "Delivered a configurable Salesforce REMS platform with admin console capabilities, enrollment automation, and a secure Experience Cloud portal for external stakeholders.",
    outcomes: [
      "REMS program setup and user management",
      "Program switching and configuration-driven workflows",
      "External Experience Cloud portal",
      "Dynamic UI layouts",
      "Enrollment automation",
      "Case-to-account mapping",
      "Duplicate checks and participant association",
      "Document submission workflows",
    ],
    keywords: [
      "Salesforce REMS platform",
      "Experience Cloud healthcare portal",
      "Salesforce enrollment automation",
      "Life sciences compliance workflows",
      "Metadata driven Salesforce configuration",
    ],
    technologies: [
      "Salesforce CRM",
      "Experience Cloud",
      "Apex",
      "LWC",
      "Flows",
      "Metadata-driven configuration",
    ],
  },
  {
    slug: "field-operations-platform-mobile-maps",
    title: "Field Operations Platform with Mobile & Maps",
    industry: "Field Service / Mobile Operations",
    period: "Representative Delivery Experience",
    summary:
      "Delivered a Salesforce field operations platform with mobile workflows, map-based assignment, geo-audit capabilities, and supervisor visibility.",
    outcomes: [
      "Salesforce mobile workflows",
      "Offline-ready execution",
      "Map-based routing and assignment",
      "Nearest-resource logic",
      "GPS-tagged visit attempts",
      "Geo-audit workflows",
      "Supervisor dashboards",
      "External survey integration",
    ],
    keywords: [
      "Salesforce field operations platform",
      "Salesforce mobile workflow delivery",
      "Map based routing Salesforce",
      "Geo audit Salesforce solution",
      "Forsta Salesforce integration",
    ],
    technologies: [
      "Salesforce",
      "Apex",
      "LWC",
      "Flows",
      "Salesforce Mobile",
      "Google Maps APIs",
      "REST APIs",
    ],
  },
];
